### ISSUE TITLE
Minimum requirements could be more intuitive

### ISSUE THREAD

**Issue by mjaakko** [UniversityOfHelsinkiCS/labtool#1006]
Currently final review has to be submitted before minimum requirements are shown. Final review has to be then edited to show missing minimum requirements to the student.

This could be improved by showing missing minimum requirements in final review and updating the minimum requirement list when checklist items are selected.

Also checklists should maybe have an icon to highlight items that are minimum requirements.

**Comment by hisahi** [comment]
now tracked in #1036 and #1039
