### ISSUE TITLE
Hide (or gray out) My Courses if the list is empty?

### ISSUE THREAD

**Issue by gotonode** [UniversityOfHelsinkiCS/labtool#1021]
This is a suggestion, feel free to close this issue if the client doesn't want it.

I was thinking that we could either hide the My Courses -section, either the Student or the Teacher -variant, when it doesn't contain any elements. Or, alternatively, just gray it out.

But what to show if the user is not a student or a teacher on any course? Perhaps just a message saying that this is the case.

**Comment by hisahi** [comment]
Done in #1080
