### ISSUE TITLE
Minimum requirements improvements

### ISSUE THREAD

**Issue by mjaakko** [UniversityOfHelsinkiCS/labtool#1032]
* Minimum requirements should be visible on final review page before submitting review
* Final review should have a field for grade (which is always optional)
* Student list should have a column for grade (should be visible only if at least one student has grade)
* Minimum requirement checklist items should not specify points, but instead effect on grade (e.g. 2 -> max grade 3)
* Minimum requirements should be visible when creating review, for example by having a different section for minimum requirements or displaying an icon on minimum requirements.

*This issue should be split into multiple smaller issues*

**Comment by hisahi** [comment]
Make sure to include Grade in CSV

**Comment by hisahi** [comment]
Split into #1036, #1037, #1038, #1039
