### ISSUE TITLE
Internal server error when copying and saving checklists from another week or course

### ISSUE THREAD

**Issue by Mamelukki** [UniversityOfHelsinkiCS/labtool#1060]
Copying an existing checklist from another week or course and saving it causes an internal server error

**Comment by hisahi** [comment]
This seemingly only affects the test data and is likely caused by either a bug in Sequelize or postgres with auto-increment of IDs not working correctly, causing conflicts whenever any new items are added, which lead to primary key constraint failures, which lead to the error discussed here

**Comment by hisahi** [comment]
Fixed in #1059
