### ISSUE TITLE
Use github API to sort out people from code reviews who have issues disabled in their repos

### ISSUE THREAD

**Issue by laimikko1** [UniversityOfHelsinkiCS/labtool#380]

**Comment by mjaakko** [comment]
As issues are automatically enabled for new repositories, I think we should have a different approach to this. Maybe use GitHub API on frontend to check when registering for a course if the user has somehow managed to disable issues and show a big scary warning that they will not be able to participate in code reviews and thus not be able to receive points from them.

**Comment by hisahi** [comment]
Done in #804
