### ISSUE TITLE
Cancel button on the 'Edit course' page redirects to Courses instead of CoursePage

### ISSUE THREAD

**Issue by ootee** [UniversityOfHelsinkiCS/labtool#454]
Cancel button should direct back to the CoursePage, just like Save button does. Now it directs to view of all courses.

Also, should the save button redirect back to CoursePage or just save the changes? 

Now if you want to setup the final review, you first go to 'edit course', then click on the checkbox for the course to have a final review, then you click Save, then you are redirected back to the course page, then you need to click 'edit course' again and then click 'create new checklist' to edit the checklist for final review.

**Comment by hisahi** [comment]
Fixed in #739 which is now in master
