### ISSUE TITLE
Login should use Shibboleth / SAML2

### ISSUE THREAD

**Issue by ValheKouneli** [UniversityOfHelsinkiCS/labtool#485]
For security reasons, login should be done using SAML: [Link to University's page explaining SAML](https://wiki.helsinki.fi/pages/viewpage.action?pageId=197657106)

Why this is recommended:
+ if you have logged in to Moodle, Weboodi etc, you don't have to log in again
+ __if there is a security breach related to this software, if does not leak passwords etc.__

**Comment by qzuw** [comment]
done with #563
