### ISSUE TITLE
Creating new code review UI is unintuitive

### ISSUE THREAD

**Issue by ValheKouneli** [UniversityOfHelsinkiCS/labtool#487]
When you create new code review, it shows "create" and "assign selected randomly" buttons, but no "save" button.

Also, teacher can apparently see all code reviews even if they are not set to be visible.

**Comment by qzuw** [comment]
In addition, it is not obvious to user that code reviews need to be activated separately. There should be clear instructions what to do to activate course and/or it should be easy to obvious if code review is unactivated.

**Comment by hisahi** [comment]
Refactor the code review table to <StudentTable /> and make it obvious that a given code review is not activated (and that you **have** to select one). Notification in bottom of page???

**Comment by yumoL** [comment]
Also dropdown of the tag filter to show the tags that can be selected

**Comment by hisahi** [comment]
Fixed in #729
