### ISSUE TITLE
"Show unassigned students" cannot filter when creating new code review.

### ISSUE THREAD

**Issue by Chamion** [UniversityOfHelsinkiCS/labtool#495]
When creating a new code review.

## Expected
Clicking the filter button shows students who are not yet set to be assigned in the new code review.

## Actual
Clicking the fliter button shows students who are not yet assigned in the currently opened code review or no students if no code review is opened.

A workaround for this would be to have the create button create an empty code review instead of letting the user initialize values. This way the user is forced to use the side of the functionality that works.

**Comment by hisahi** [comment]
Fixed in #871
