### ISSUE TITLE
If two checklist rows have the same name, the checklist does not work properly

### ISSUE THREAD

**Issue by ValheKouneli** [UniversityOfHelsinkiCS/labtool#506]
### How to replicate:

Create a checklist that has two rows with the same description (name). (For example: "documentation" under "testing" group and "documentation" under "code" group.) Use the checklist and toggle between checkmarks. See, how the text and points show wrong.

When clicking on a checkbox...

expected: points are awarded for that checkbox.

actual: points are awarded as if all checkboxes who share the name were toggled.

### How to fix:

When checks are saved, information about both row name and group name should be saved, not only row name.

**Comment by hisahi** [comment]
This is no longer relevant due to the use of IDs for checks
