### ISSUE TITLE
instructor needs to see student participation to prior instances

### ISSUE THREAD

**Issue by qzuw** [UniversityOfHelsinkiCS/labtool#526]
Instructor needs a way to see student details.
- ~student id is needed for registering results~ #595
- ~email in case there is need to contact students in bulk or without connection to review~ #595
- participation to prior instances of current course for additional instructions and/or requirements

**Comment by hisahi** [comment]
Email still needs to be made visible

**Comment by hisahi** [comment]
This issue now only concerns "participation to prior instances of current course for additional instructions and/or requirements". ID and email now under #595

**Comment by hisahi** [comment]
Pushed to master in #637
