### ISSUE TITLE
Student list on course instance page uses too much vertical space

### ISSUE THREAD

**Issue by qzuw** [UniversityOfHelsinkiCS/labtool#528]
At least replace some images with text or rework listing to use less vertical space otherwise.

**Comment by gotonode** [comment]
We need to remove ID and email from this listing, as they only add to the bulk and are not needed here.

**Comment by gotonode** [comment]
I'll consider adding a tooltip (on mouse hover) somewhere which would show the student's ID and email.

**Comment by gotonode** [comment]
The client also wants to be able to access the "review"-button without the need to scroll. Of note is that the system is often being used with 50 % of the screen's width in other use (reviewing the student's project).

**Comment by hisahi** [comment]
Does "vertical space" actually refer to "horizontal space" here?

**Comment by qzuw** [comment]
vertical refers to vertical, horizontal is another issue.

Instructor column seems to be currently reason for using extra vertical space

**Comment by hisahi** [comment]
![kuva](https://user-images.githubusercontent.com/32158431/65626156-bfc68f80-dfd5-11e9-8718-1e7e5c5da94f.png)
Most vertical space seems to be taken up by the project info field which also contains the tags and the button to edit tags. The instructor and name columns also take up a lot of vertical space.

**Comment by hisahi** [comment]
Somewhat fixed in #647 in terms of vertical space usage
