### ISSUE TITLE
Tag color options should be clear

### ISSUE THREAD

**Issue by qzuw** [UniversityOfHelsinkiCS/labtool#530]
Currently you can only try to guess what colors are available, and if you guess wrong, your tag will be gray.

User request was being able to use html color codes.

**Comment by gotonode** [comment]
Either add a color swatch, or a list of colors to choose from. The color swatch would work with HTML color codes, such as `#fff` or `#AB88CC`. Preferably save the code in uppercase.

**Comment by hisahi** [comment]
Solved in #632
