### ISSUE TITLE
if page content is wider than browser window, there is no way to see excess part

### ISSUE THREAD

**Issue by qzuw** [UniversityOfHelsinkiCS/labtool#537]
Either we need way to scroll sideways if necessary (preferable) or should switch to mobile view much earlier

**Comment by hisahi** [comment]
Fixed in #605

**Comment by hisahi** [comment]
Reopened:

The table must be made easier to scroll horizontally (display scrollbar always on screen?).

**Comment by hisahi** [comment]
Pushed to master in #637
