### ISSUE TITLE
Course page's "You have not activated this course" banner is broken

### ISSUE THREAD

**Issue by cxcorp** [UniversityOfHelsinkiCS/labtool#553]
When a student visits the course page of an inactive course, he is presented with a _"This course has not been activated"_ [banner](https://github.com/UniversityOfHelsinkiCS/labtool/blob/ec802f9165f8030840874017bb605ef3bafb09ad/labtool2.0/src/components/pages/CoursePage.js#L736). Commit 5120cf00 introduced a similar [banner](https://github.com/UniversityOfHelsinkiCS/labtool/blob/ec802f9165f8030840874017bb605ef3bafb09ad/labtool2.0/src/components/pages/CoursePage.js#L519) for the teacher: _"You have not activated this course."_

This banner was later broken, possibly in 4cb9fc57 or some commit in which the reducer or a mapStateToProps was changed.

Currently, the snippet looks like the following:

https://github.com/UniversityOfHelsinkiCS/labtool/blob/ec802f9165f8030840874017bb605ef3bafb09ad/labtool2.0/src/components/pages/CoursePage.js#L513-L525

The message never renders, because the condition for rendering the message is essentially `this.props.courseInstance.active && this.props.courseData.data === null `. Not only are these two conditions mutually exclusive for a user with the `teacher` role, but the `active` check is also missing a negation.

As a solution, this snippet could either be completely removed as dead code, or fixed with a construct like:

```
{!this.props.selectedInstance.active && (
  <div>
    <Message compact>
    <Message.Header>You have not activated this course.</Message.Header>
    </Message>
  </div>
)}
```

Which one would be more appropriate?

**Comment by hisahi** [comment]
Pushed to master in #637
