### ISSUE TITLE
Email students feature

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#573]
Instructors should be able to select students from a list, type a message and then have that email sent to all selected students.

**Comment by hisahi** [comment]
Done in #605

**Comment by hisahi** [comment]
Reopened:

needs testing on staging with real emails.

**Comment by hisahi** [comment]
tested, confirmed functional on staging

**Comment by hisahi** [comment]
"Send to instructors" checkbox

**Comment by yumoL** [comment]
The email should have defaulted text which shows that the email is sent via the labtool and shouldn't be replied to.

**Comment by hisahi** [comment]
Done in #687
