### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mjaakko** [UniversityOfHelsinkiCS/labtool#584]
Update dependencies to fix security issues https://github.com/UniversityOfHelsinkiCS/labtool/network/alerts

**Comment by gotonode** [comment]
I enabled GitHub's automated security fix -feature. It should create a pull request, which will be automatically tested by Travis, and which can later be merged if all tests pass. It only increments the version numbers.

Does anyone see an issue with this approach? If not, I'll merge the PR if all tests pass.

**Comment by gotonode** [comment]
It created 8 PR's from the security issues. They can be viewed here:

https://github.com/UniversityOfHelsinkiCS/labtool/pulls/app%2Fdependabot

Travis is testing each one separately.

**Comment by mjaakko** [comment]
Seems that the automated security fix creates pull requests to `master` branch while development should happen in `trunk` branch.

**Comment by hisahi** [comment]
Dependabot should have an option for the target branch.

**Comment by gotonode** [comment]
I merged the PR's into `trunk` and removed the auto-created branches. The new Dependabot config file should now automatically target `trunk`.

**Comment by gotonode** [comment]
Remember to update your dependencies. If you're using an IDE like `WebStorm`, it'll automatically prompt you to do so once it detects changes in `package.json`.

**Comment by hisahi** [comment]
Done in #605
