### ISSUE TITLE
the instructor needs to see students' details (student id+email)

### ISSUE THREAD

**Issue by yumoL** [UniversityOfHelsinkiCS/labtool#595]
Instructor needs a way to see student details.
- student id is needed for registering results
- email in case there is need to contact students in bulk or without connection to review
( This issue includes the first two requirements of issue #526 )

**Comment by hisahi** [comment]
Done in #605

**Comment by hisahi** [comment]
Reopened:

The email/student ID need not be shown in the course table, only on student page.

**Comment by hisahi** [comment]
Pushed to master in #637
