### ISSUE TITLE
On My Page and course listing, show year in addition to period when listing courses

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#607]

**Comment by hisahi** [comment]
Pushed to master in #637

**Comment by yumoL** [comment]
The redundant period should be removed in the course listing. The period is already included in the course name in most of the courses in production.

**Comment by hisahi** [comment]
Done in #647

**Comment by hisahi** [comment]
Hide period, course titles have it already

**Comment by hisahi** [comment]
Done in #687
