### ISSUE TITLE
Instructor or student should not be able to add empty comments

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#608]

**Comment by gotonode** [comment]
Are pure whitespace comments also empty? If the user just adds a space character, should that be allowed?

I'm thinking that the check is of type:
```js
if (!comment.trim().isEmpty()) {
  // Post the comment.
}
```

**Comment by hisahi** [comment]
Yes, whitespace-only comments are considered "empty". The frontend code can simply be `required` on the input but the backend should not accept any comments with only whitespace characters or no characters at all.

**Comment by hisahi** [comment]
Pushed to master in #637
