### ISSUE TITLE
Export student table CSV as instructor

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#611]
Should contain name, student number, email, week scores etc.

**Comment by gotonode** [comment]
Also for dropped out students, or just for active students? I'm thinking that adding the functionality for dropped out students would be easy to do, but perhaps it's work that's done that does not serve any purpose. We can consult the client at spring 3 meeting.

**Comment by yumoL** [comment]
Student numbers should be in their own column

**Comment by hisahi** [comment]
Format:

Name,StudentNumber,Email,Week1,Week2,...Week7,CodeReview1,...,FinalReview

**Comment by yumoL** [comment]
For all students (both active and dropped out)

**Comment by hisahi** [comment]
Done in #871
