### ISSUE TITLE
Dropped students functionality change (system tags or a new boolean)

### ISSUE THREAD

**Issue by gotonode** [UniversityOfHelsinkiCS/labtool#614]
Currently it's a tag called `DROPPED`. If someone changes the tag's name, the system doesn't work.

Either make some tags into system tags that cannot be removed or modified, or create a boolean value into the database that indicates if the user has dropped out or not.

I assigned this EPIC, depending on the path we choose. Might require work on front, back and database.

**Comment by hisahi** [comment]
PR #622 also addresses this.

**Comment by mjaakko** [comment]
Done in #622
