### ISSUE TITLE
Link to student repository and show previous week feedback (+ instructor notes) when reviewing week

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#664]

**Comment by gotonode** [comment]
I can at least add the link to the student repo.

**Comment by gotonode** [comment]
I'll probably summon help for the second part (previous feedback). If you want, you can create a branch and start working on that feature. I'll add my contribution later.

**Comment by gotonode** [comment]
Working on this now.

**Comment by gotonode** [comment]
Will be done later today.

**Comment by hisahi** [comment]
Done in #729
