### ISSUE TITLE
If instructor is unassigned for all students, hide the instructor column

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#667]

**Comment by gotonode** [comment]
What if the instructor is the same for all students? We could hide this column then as well, and indicate the instructor elsewhere. But of course this could get complicated. Just throwing the idea out there, feel free to ignore.

**Comment by hisahi** [comment]
#669 should be implemented first

**Comment by hisahi** [comment]
Done in #712
