### ISSUE TITLE
Minimize horizontal space use of table

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#668]
* Headers: Week -> W
* Project info: strip https:// from link, strip github.com if present (replace with GitHub logo)
* Review: merge button to student name.
  * perhaps: add review links to every week and code review to access review page **directly**. (way to show if there are comments in the table??)

**Comment by gotonode** [comment]
I'll have a look see on how this develops. Screenshots will be posted and feedback gathered. The client actually wanted "Week" to be "Wk" but I agree, "W" + integer is better, as in "W1" etc.

**Comment by hisahi** [comment]
Done in #729
