### ISSUE TITLE
Improve dropped button

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#671]
"Mark as dropped/non-dropped" button should be red and perhaps right-aligned to make it harder to find. Now it's confusing and may be accidentally clicked instead of "Open all reviews".

**Comment by gotonode** [comment]
This button is rarely used (I think), but each time the page in question is loaded a big red button might not look too nice. Maybe a dark red outline, and an icon such as the "no go" one before the text?

When a student is marked as dropped, the "mark as not dropped" shouldn't be red in my opinion, but like the issue directs it shouldn't be able to be confused with the "Open all reviews" -button.

**Comment by hisahi** [comment]
Done in #712
