### ISSUE TITLE
New comment field in accordion to hide it by default

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#673]
takes too much space now

**Comment by gotonode** [comment]
Perhaps change the title to reflect all wanted changes:

- Accordion
- "Supports Markdown", move this under the Comments-title
- Move preview next to the comment field (if there's enough horizontal space)
- Place the checkbox (send to instructor only) next to the submit comment -button (left side)

**Comment by gotonode** [comment]
Regarding the checkbox, would it be an idea to make it a button like the submit comment -button? So we'd have two buttons, one used to send the comment to the student, and the other to send it to the instructor.

**Comment by hisahi** [comment]
Done in #712
