### ISSUE TITLE
Show email address when assigning instructors for course

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#676]

**Comment by gotonode** [comment]
I'll add them in the following fashion:

`First name + Last name (email@example.com)`

**Comment by gotonode** [comment]
Does someone know why this doesn't work?
```html
<Table.Cell>
  {user.firsts} {user.lastname} ({user.email})
</Table.Cell>
```

It's on the modify course staff page.

**Comment by gotonode** [comment]
It seems that `sortedUsers` doesn't contain the email address that is needed. The method `getAllUsers` in `user.js` is probably responsible for providing this data. I'll see how to add email addresses here as well.

**Comment by hisahi** [comment]
Done in #729
