### ISSUE TITLE
The teacher can see details of a student's participation in the previous instances of the course

### ISSUE THREAD

**Issue by yumoL** [UniversityOfHelsinkiCS/labtool#680]
The teacher can see the week points etc. of a student's participation in the previous instances of the course by (for example) clicking the previous participation in the BrowseReviews Page

**Comment by gotonode** [comment]
Do you want to take this issue for yourself?

**Comment by gotonode** [comment]
Once it's assigned to you, you'll be able to dictate who helps you and in what timeframe you do this.

**Comment by hisahi** [comment]
Done in #712
