### ISSUE TITLE
Markdown preview not visible unless changes are made

### ISSUE THREAD

**Issue by gotonode** [UniversityOfHelsinkiCS/labtool#723]
When checking the preview of Markdown formatting, the preview field is empty. Once changes are made to the text, the preview appears. This is only an issue once there's already some text to be previewed; otherwise it's okay.

Shouldn't it show the preview immediately once the accordion is opened down?

At least this is the case on the review student (week) -page.

**Comment by gotonode** [comment]
I tried to have a look and fiddle around with the code but couldn't figure out how to do in JS. My thinking is that it needs to load the content when the accordion is opened. I don't think it's necessary to load it when the page loads, but that could also be an option.

I'll assign this to myself and see if I can't figure something out during this sprint. It's also good for learning.

**Comment by hisahi** [comment]
Fixed in #729
