### ISSUE TITLE
Redundant period in course lists should be removed

### ISSUE THREAD

**Issue by yumoL** [UniversityOfHelsinkiCS/labtool#748]
Make a special case for ohjelmistotekniikka-course, only add a period to the ohjelmistotekniikka-course

**Comment by gotonode** [comment]
Should we generalize the special case somehow so that if this same situation rises with new courses in the future (who knows), it could be applicable to those as well?

Hard-coding that course's data just doesn't seem quite right.

**Comment by yumoL** [comment]
> Should we generalize the special case somehow so that if this same situation rises with new courses in the future (who knows), it could be applicable to those as well?
> 
> Hard-coding that course's ID (etc) just doesn't seem quite right.

According to the client, the ohjelmistotekniikka course is the only special case we need to care for now. Adding period after the course name whose ohid includes "TKT20002" may be enough. Another way is to check if the course name has round brackets (it seems the period is always written inside  brackets), if not, then add the period.

**Comment by gotonode** [comment]
Understood. Client's wishes are the law. ☺

**Comment by gotonode** [comment]
I think the round brackets option would be more ideal. But what happens if/when the course ID changes? Also, other courses might get round brackets in their names in the future. So either option has pros and cons. You can choose whichever you think is best.

**Comment by hisahi** [comment]
Done in #789
