### ISSUE TITLE
Improve tags

### ISSUE THREAD

**Issue by yumoL** [UniversityOfHelsinkiCS/labtool#749]
- Show only the tags which are used in the course.
- We don't need dropdown in the tag filter, all tags which are used in the course should be shown at the same time. The teacher can click the tag label to activate the filter.
- Tag labels should have a cross and the teacher can click the cross to remove the tag.

**Comment by gotonode** [comment]
I was thinking that maybe having a cross would require too much accuracy.

How about making each tag toggleable, as in you can click anywhere on the tag to select it, and clicking it again will deselect it? Once selected, it should show this new state clearly somehow. A border, more intense color or a checkmark next to the tag's name are some examples.

**Comment by hisahi** [comment]
Done in #789
