### ISSUE TITLE
Update database schema in wiki

### ISSUE THREAD

**Issue by mjaakko** [UniversityOfHelsinkiCS/labtool#769]
This should be updated: https://github.com/UniversityOfHelsinkiCS/labtool/wiki/Database-schema

Also, add database schema source to GitHub so that it's easier to edit without having to recreate it every time.

**Comment by gotonode** [comment]
I wholeheartedly support the second part. We can add the source and a link to the site used to generate the diagram on the aforementioned page.

**Comment by hisahi** [comment]
Documentation in general needs updating

**Comment by hisahi** [comment]
I updated the schema for now, a new issue is better for documentation updates in general
