### ISSUE TITLE
Checklist "Total Max Points" should be rounded

### ISSUE THREAD

**Issue by HeikkiHei** [UniversityOfHelsinkiCS/labtool#811]
Issue noticed while editing "Aineopintojen harjoitustyö: Tietokantasovellus" checklists.

When editing checklists, "Total Max Points" does not round to reasonable digits, if no maximum points are given to the week. When maximum points are set, the "Total Max Points" is also set according to that, rather than as a sum of checkpoints.

Current behavior: When adding partial points from checkpoints, the "Total Max Points" is not rounded to reasonable digits, but is given as for example 2.000004 due to floats.

Expected behavior: When adding partial points from checkpoints, the "Total Max Points" is rounded to 2.00 in this example.

**Comment by hisahi** [comment]
Fixed in #804
