### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by gotonode** [UniversityOfHelsinkiCS/labtool#836]
I'll read the necessary accessibility materials and update our wiki accordingly. I'll be checking our project while doing so to see if it adheres to them (or any guidelines).

This is an ongoing issue but I'll close this one once the team has been acquainted with the new wiki entry.

**Comment by gotonode** [comment]
https://github.com/UniversityOfHelsinkiCS/labtool/wiki/Accessibility-guidelines

**Comment by mjaakko** [comment]
Few things to consider:
* How does `react-router` handle accessibility?
* Does Semantic UI support accessibility out of box?
* Semantic HTML tags such as `main` and `nav` are currently used incorrectly, e.g. the document should contain only one `main` tag
