### ISSUE TITLE
Teacher should be able to see if student's Github repo exists

### ISSUE THREAD

**Issue by mjaakko** [UniversityOfHelsinkiCS/labtool#850]

**Comment by hisahi** [comment]
How do we want to implement this? Show a warning of some kind? This likely requires the flag to be stored in the backend...

**Comment by hisahi** [comment]
* Add boolean field to backend (repoExists), which is true for GitHub repos that exist, false for ones that don't and null for non-GitHub, etc.
* Set this repoExists flag from the frontend
* Display warning to teacher if repoExists **is false**

**Comment by mjaakko** [comment]
> * Add boolean field to backend (repoExists), which is true for GitHub repos that exist, false for ones that don't and null for non-GitHub, etc.

Maybe this should be an enum? I think we don't want to show a warning for valid non-GitHub repos.

**Comment by hisahi** [comment]
> 
> 
> > * Add boolean field to backend (repoExists), which is true for GitHub repos that exist, false for ones that don't and null for non-GitHub, etc.
> 
> Maybe this should be an enum? I think we don't want to show a warning for valid non-GitHub repos.

Possibly, but I did state that only `false` should cause a warning, and not `null`.

**Comment by hisahi** [comment]
Done in #883
