### ISSUE TITLE
If a course has no dropped students, statistics should not include number of dropped students or sum of students

### ISSUE THREAD

**Issue by mjaakko** [UniversityOfHelsinkiCS/labtool#851]
Currently statistic include sum of students and number of dropped students even if there are no dropped students.

**Comment by gotonode** [comment]
I'll take this one as this feature was made by me.

Good thing someone took notes because I can't remember the client asking for this.

**Comment by mjaakko** [comment]
Also, invalid registrations should not be included at all in statistics

**Comment by hisahi** [comment]
Fixed in #933
