### ISSUE TITLE
Move email send and CSV export buttons somewhere more visible

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#894]
For example, they could be in "modify selected students". They're hard to find for users right now

**Comment by mjaakko** [comment]
"modify selected students" should be renamed if it also contains email and CSV export functions as they are not really modifying anything.

**Comment by hisahi** [comment]
That (renaming it "student tools"?), or alternatively the buttons could also be at the top of the table as well as the bottom.

**Comment by hisahi** [comment]
We should also compact the panel a bit, since there is too much vertical spacing. Perhaps the tag/instructor buttons could be next to the dropdown too, and compact it down to 2 rows.

**Comment by hisahi** [comment]
Done in #990
