### ISSUE TITLE
Tags that would cause the student table to be blank should be grayed out in filter options

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#900]
If there is a tag X that causes the student table to be empty when we filter using that tag, it should be grayed out. This should also work if we already filter by tag Y, and there are no students with both tag X and Y.

**Comment by mjaakko** [comment]
Is there any need to show these tags at all if they are not used by any student?

**Comment by hisahi** [comment]
> Is there any need to show these tags at all if they are not used by any student?

Good point, thus this is more relevant when we already have one filtering tag. Making tags disappear then could be confusing, though.

**Comment by gotonode** [comment]
This is a very low priority issue but it's good that it's here.

**Comment by hisahi** [comment]
Done in #1054
