### ISSUE TITLE
Use locale sorting when sorting students in the table

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#902]
In the Finnish locale, this means V and W are considered to be of the same rank, except when they are the only difference (in which case W is after V).

Edit: always use Finnish locale if available

**Comment by hisahi** [comment]
The sorting function needs to use `localeCompare`, more specifically

**Comment by gotonode** [comment]
Always use Finnish locale.

**Comment by hisahi** [comment]
Done in #1005
