### ISSUE TITLE
Add "edit code reviews" button to course page

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#914]
Buttons like "modify tags", "modify code reviews" etc. could be displayed as round icon buttons on the main course page, like and next to the "modify course instance" button

Edit: only "modify code reviews" is required, and it should be next to "modify course" button

**Comment by hisahi** [comment]
These buttons could also have tooltips. My suggestions for icons are

* manage assistant teachers: `id badge`
* edit code reviews: `shuffle`?
* edit checklists: `clipboard list`
* edit tags: `tags`

**Comment by gotonode** [comment]
For accessibility purposes, should we consider adding text as well as the icon? If we add text, it shouldn't be the same as the tooltip. The tooltip should, in case we add text, provide additional information.

But then again, the client said instructors don't need accessibility...

**Comment by hisahi** [comment]
Done in #990
