### ISSUE TITLE
Make "total max points" more intuitive on checklist creation

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#953]
It should be above the maximum points input field, which should tell the user that only editing that will change the maximum points. It should also be renamed to "total points from checks", etc.

**Comment by yumoL** [comment]
remove back to in Progress due to some necessary fixes
- should not show "maximum points for this week" in the final review
- the defaulted maximum points should be the defaulted weekly points in final review

**Comment by hisahi** [comment]
Done in #990
