### ISSUE TITLE
Checklists can have subchecklists

### ISSUE THREAD

**Issue by hisahi** [UniversityOfHelsinkiCS/labtool#956]
For example, when an item is checked, there are further options to check.

**Comment by mjaakko** [comment]
This needs planning: How are points counted for subchecklists?

**Comment by hisahi** [comment]
This is probably best implemented as checks that can have a prerequisite check. If the prerequisite is not checked, any checks that have that as a prerequisite cannot be checked either, so they could be hidden from the UI (and if a category only has those hidden checks, it would be hidden entirely).

For example, there could be a check on whether there is a README. We can then add a new category for README checks and set all of those checks to have the "README exists" check as a prerequisite. Perhaps the UI could also have some way to easily add a prerequisite to all checks in some category.

**Comment by hisahi** [comment]
Done in #1059
