### ISSUE TITLE
Gitlab repository should not be checked when using github api

### ISSUE THREAD

**Issue by yumoL** [UniversityOfHelsinkiCS/labtool#982]

**Comment by gotonode** [comment]
Seems interesting! Will tackle next week.

**Comment by hisahi** [comment]
This concerns checking whether the issues are enabled or not. It should only check if the repository is actually on GitHub

**Comment by hisahi** [comment]
This is of high priority, so I will do this this week

**Comment by gotonode** [comment]
Yes, I understand.

**Comment by gotonode** [comment]
Okay, unless I can do it this week (time-permitting of course).

**Comment by hisahi** [comment]
We'd like this to be in the current master<-trunk

**Comment by gotonode** [comment]
I might have time to do this this night. But go ahead if that's too late.

**Comment by hisahi** [comment]
> 
> 
> I might have time to do this this night. But go ahead if that's too late.

If you can do this tonight, that should be early enough, since the master merge will be tomorrow on Friday

**Comment by hisahi** [comment]
Fixed in #990
